config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'woolentries#index'
  get 'woolentries/listall' => "woolentries#listall"
  post 'woolentries/searchmap' => "woolentries#searchmap", as: :searchmap

  resources :woolentries

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :woolentrys
end

app/models/woolentry.rb
class Woolentry < ActiveRecord::Base

  belongs_to :user

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/maingame_controller.rb
class MaingameController < ApplicationController
  #require_dependency 'bot'

  def index
    @posts = Woolentry.all
        @hash = Gmaps4rails.build_markers(@posts) do |wool, marker|
          marker.lat wool.lat
          marker.lng wool.long
          marker.json({ :id => wool.id })
          marker.infowindow render_to_string(:partial => "markertext", :locals => { :p => wool})
          marker.picture({
   "url" => 'https://static.maplewiki.net/6/6a/Red_Ball_of_Yarn.gif',
   "width" =>  '16',
   "height" => '16'
   })
        end
  end



  def create

    @inputpointname = params[:pointname]
    @inputpointwhere = params[:pointwhere]
    @inputpointwhat = params[:pointwhat]
    @mapinfo = Geocoder.search(@inputpointwhere)
    @newwool = Woolentry.new
    @newwool.lat = @mapinfo[0].latitude
    @newwool.long = @mapinfo[0].longitude
    @newwool.desc = @inputpointname
    @newwool.save
    respond_to do |format|
      format.js

    end


  end
end

app/controllers/woolentries_controller.rb
class WoolentriesController < ApplicationController


def searchmap
  @search = params[:searchinput]


  respond_to do |format|

   format.js
  format.html
  end

end

def showpopupmodal


  respond_to do |format|

   format.js
  format.html
  end
end



  def edit

  @cwool = Woolentry.find_by_id(params[:id])

  respond_to do |format|

   format.js
  format.html
  end


  end

  def listall
  @wools = Woolentry.all
  respond_to do |format|

   format.js
  format.html
end

  end


  def destroy

    @deletewool = Woolentry.find_by_id(params[:id])
    @deletewoolid = @deletewool.id
    @deletewool.destroy

    respond_to do |format|

     format.js
    format.html
  end



  end

  def index
    @posts = Woolentry.all
        @hash = Gmaps4rails.build_markers(@posts) do |wool, marker|
          marker.lat wool.lat
          marker.lng wool.long
          marker.json({ :id => wool.id })
          marker.json({ :person => wool.person })

          marker.infowindow render_to_string(:partial => "markertext", :locals => { :p => wool})
          marker.picture({
   "url" => 'https://static.maplewiki.net/6/6a/Red_Ball_of_Yarn.gif',
   "width" =>  '16',
   "height" => '16'
   })
        end
  end



def update

  @inputphonenum = params[:phonenum]
  @inputpointname = params[:pointname]
  @inputpointwhere = params[:pointwhere]
  @inputpointwhat = params[:pointwhat]
  @mapinfo = Geocoder.search(@inputpointwhere)
  @savable = true

  if @mapinfo == []
    @error = "couldnt find location"
    @savable = false
  end

  if @inputphonenum == ""
    @error = "phone number is empty"
    @savable = false

  end

  if @inputpointname == ""
    @error = "name number is empty"
    @savable = false

  end

  if @inputpointwhat == ""
    @error = "wool was empty"
    @savable = false

  end

  if @savable
  @newwool = Woolentry.find_by_id(params[:id])
  @newwool.lat = @mapinfo[0].latitude
  @newwool.long = @mapinfo[0].longitude
  @newwool.desc = @inputpointwhat
  @newwool.person = @inputpointname
  @newwool.phonenum = @inputphonenum
  @newwool.save

  end
  # redirect_to '#index', notice: "Record updated"
   respond_to do |format|
     format.js
     format.html
   end


end

  def create
    @inputphonenum = params[:phonenum]
    @inputpointname = params[:pointname]
    @inputpointwhere = params[:pointwhere]
    @inputpointwhat = params[:pointwhat]
    @mapinfo = Geocoder.search(@inputpointwhere)
    @savable = true

    if @mapinfo == []
      @error = "couldnt find location"
      @savable = false
    end

    if @inputphonenum == ""
      @error = "phone number is empty"
      @savable = false

    end

    if @inputpointname == ""
      @error = "name number is empty"
      @savable = false

    end

    if @inputpointwhat == ""
      @error = "wool was empty"
      @savable = false

    end

    if @savable
    @newwool = Woolentry.new
    @newwool.lat = @mapinfo[0].latitude
    @newwool.long = @mapinfo[0].longitude
    @newwool.desc = @inputpointwhat
    @newwool.person = @inputpointname
    @newwool.phonenum = @inputphonenum
    @newwool.save
    end

    # redirect_to '#index', notice: "Record added"
     respond_to do |format|
       format.js
       format.html
     end


  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maingame_helper.rb
module MaingameHelper
end

app/helpers/woolentries_helper.rb
module WoolentriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>

  <title>Wool</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="apple-mobile-web-app-capable" content="yes">

  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- <%=subscribe_to "/test"%> -->

</head>

<body>





  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Wool</a>
        <ul class="nav navbar-nav">

      </ul>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
            <li><%=link_to("List all entries",{ :action => "listall"},{ :remote => true,:method => :get, :class => ""}) %> </li>
          <li><a href="#" onclick="javascript:$('#addwoolmodal').modal('show');">Add new Wool pickup Entry</a></li>
        </ul>

          <%= form_tag({action: "searchmap"}, {class: "navbar-form navbar-right",remote: true}) do %>

        <%= text_field_tag 'searchinput', '', class: "form-control",placeholder: "Search.." %>
        <%= submit_tag "Send", 'data-disable-with' => 'Sending', class: 'btn btn-primary' %>


        <%end%>
      </div>
    </div>
  </nav>


  <!-- <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %> -->



<%= yield %>

</body>
</html>

app/views/woolentries/_listpart.html.erb
    <tr>
      <td><%=wools.id%></td>
      <td><%=wools.person%></td>
      <td><%=wools.phonenum%></td>
      <td><%=wools.desc%></td>
      <th><a target="_blank" href="https://www.google.co.za/maps/dir//<%=wools.lat%>,<%=wools.long%>/@<%=wools.lat%>,<%=wools.long%>,13z">click</a></th>
    </tr>
    <!-- <tr>
      <td>2</td>
      <td>Column content</td>
      <td>Column content</td>
      <td>Column content</td>
    </tr>
    <tr class="info">
      <td>3</td>
      <td>Column content</td>
      <td>Column content</td>
      <td>Column content</td>
    </tr>
    <tr class="success">
      <td>4</td>
      <td>Column content</td>
      <td>Column content</td>
      <td>Column content</td>
    </tr>
    <tr class="danger">
      <td>5</td>
      <td>Column content</td>
      <td>Column content</td>
      <td>Column content</td>
    </tr>
    <tr class="warning">
      <td>6</td>
      <td>Column content</td>
      <td>Column content</td>
      <td>Column content</td>
    </tr>
    <tr class="active">
      <td>7</td>
      <td>Column content</td>
      <td>Column content</td>
      <td>Column content</td>
    </tr> -->

app/views/woolentries/_markertext.html.erb
<ul><%= p.person %></ul>
<ul><%= p.phonenum %></ul>


<ul><%= p.desc %></ul>
<ul><a target="_blank" href="https://www.google.co.za/maps/dir//<%=p.lat%>,<%=p.long%>/@<%=p.lat%>,<%=p.long%>,13z">click for Directions</a></ul>
<ul><%= button_to 'edit' , edit_woolentry_path(p), :method => :get, :remote => true,:class => 'btn btn-primary' %></ul>

<ul><%= button_to 'delete' , woolentry_path(p), :method => :delete, :remote => true,:class => 'btn btn-primary' %></ul>

app/views/woolentries/create.js.erb
<%if @savable %>
var marker = Gmaps.store.handler.addMarker({
  'lat': "<%=@mapinfo[0].latitude %>",
  'lng': "<%=@mapinfo[0].longitude%>",
  'json': "<%={ :id => @newwool.id }%>",
  'picture': {
    'url': 'https://static.maplewiki.net/6/6a/Red_Ball_of_Yarn.gif',
    'width': 32,
    'height': 32,
    'title': "new test"
  },
  'infowindow': "<%=j render 'markertext', :p => @newwool %>"
});


console.log("test1");
Gmaps.store.markers.push(marker);
console.log('test3');
marker.serviceObject.set('id', "<%=@newwool.id%>");
marker.serviceObject.set('person', "<%=@newwool.person%>");
Gmaps.store.handler.addMarker(marker);
$('#addwoolmodal').modal('hide');
<%else%>

  $('.alert').remove();

  $('#addwoolmodal').prepend("<p class='alert alert-danger'><%=@error%> </p>");


<%end%>

app/views/woolentries/destroy.js.erb
markermoo = _.find(Gmaps.store.markers, function(obj) { return obj.serviceObject.id == "<%=@deletewoolid%>" });
Gmaps.store.handler.removeMarker(markermoo);
var index = Gmaps.store.markers.indexOf(markermoo);
Gmaps.store.markers.splice(index,1);

app/views/woolentries/edit.html.erb
<div class="col-lg-6">
  <%= form_tag woolentry_path(@cwool), :method => :put do %>

<form class="form-horizontal">
  <fieldset>
    <legend>Legend</legend>
    <div class="form-group">
      <label for="inputName" class="col-lg-2 control-label">Name</label>
      <div class="col-lg-10">
        <%= text_field_tag 'pointname', @cwool.person, size: 75, class: "form-control",placeholder: "name" %>
      </div>
    </div>

    <div class="form-group">
      <label for="inputName" class="col-lg-2 control-label">Number</label>
      <div class="col-lg-10">
        <%= text_field_tag 'phonenum', @cwool.phonenum, size: 75, class: "form-control",placeholder: "011" %>
      </div>
    </div>

    <div class="form-group">
      <label for="inputlocation" class="col-lg-2 control-label">Location</label>
      <div class="col-lg-10">
        <%= text_field_tag 'pointwhere',"#{@cwool.lat} , #{@cwool.long}", size: 75, class: "form-control", placeholder: "location" %>
      </div>
    </div>

    <div class="form-group">
      <label for="textArea" class="col-lg-2 control-label">Wool</label>
      <div class="col-lg-10">
        <%= text_field_tag 'pointwhat', @cwool.desc, size: 75, class: "form-control",placeholder: "wool" %>
        <span class="help-block">A longer block of help text that breaks onto a new line and may extend beyond one line.</span>
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <%= submit_tag "Send", 'data-disable-with' => 'Sending', class: 'btn btn-primary' %>

      </div>
    </div>
  </fieldset>
</form>
<%end%>
</div>

app/views/woolentries/edit.js.erb
$('#editwoolmodal').remove();
$('#modalstorage').append("<%=j render :partial => 'woolentries/modalparts/editwoolmodal',:@cwool => @cwool %>");
$('#editwoolmodal').modal('show');

app/views/woolentries/index.html.erb
<div id="modalstorage">
<%= render :partial => 'woolentries/modalparts/addwoolmodal' %>

</div>



<script src="https://maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script>
<script src="https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
<script src='https://google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->


  <div id="map" style='width: device-width; height: 600px;'></div>







<script>
Gmaps.store = {};

var handler;

Gmaps.store.handler = Gmaps.build('Google');

Gmaps.store.handler.buildMap({
  provider: {
    Zoom: 3,
    disableDefaultUI: false
  },
  internal: {
    id: 'map'
  }
}, function() {
  var testvar;
  testvar = Gmaps.store.handler.addMarker({
        'lat': -55.109555,
        'lng': -155.050408,
        'picture': {
          'url': 'https://static.maplewiki.net/6/6a/Red_Ball_of_Yarn.gif',
          'width': 32,
          'height': 32
        },
        'infowindow': "default"
      });
      testvar.serviceObject.visible = false;
  Gmaps.store.markers = Gmaps.store.handler.addMarker(testvar);



  //handler.map.centerOn(handler.markers);

  markers = <%=raw @hash.to_json %>;
  Gmaps.store.markers = markers.map(function(m) {
  marker = Gmaps.store.handler.addMarker(m);
  marker.serviceObject.set('id', m.id);
  // marker.setMap(Gmaps.store.handler);
  marker.serviceObject.set('person', "" + m.person); // You can add other attributes using set
  return marker;
});


  Gmaps.store.handler.bounds.extendWith(Gmaps.store.markers);
  Gmaps.store.handler.fitMapToBounds();
});
$(document).ready(function(){
  // $('.modal-addwool').modal('show');
});
  </script>

app/views/woolentries/listall.html.erb
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>#</th>
      <th>Donator Name</th>
      <th>Donator Phone Number</th>
      <th>Donator Wool</th>
      <th>Route to Address</th>
    </tr>
  </thead>
  <tbody>

<% @wools.each do |l| %>
<%= render 'listpart', :wools => l %>

<%end %>

</tbody>
</table>

app/views/woolentries/listall.js.erb
$('#listwoolmodal').remove();
$('#modalstorage').append("<%=j render :partial => 'woolentries/modalparts/listwoolmodal',:@wools => @wools %>");
$('#listwoolmodal').modal('show');

app/views/woolentries/modalparts/_addwoolmodal.html.erb
<div id="addwoolmodal" class="modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
        <h4 class="modal-title">Add new wool Location</h4>
      </div>
      <div class="modal-body">



        <%= form_tag({action: "create", method: "post"},{class: "form-horizontal",remote: true }) do %>

        <fieldset>
          <legend>New Info</legend>
          <div class="form-group">
            <label for="inputName" class="col-lg-2 control-label">Name</label>
            <div class="col-lg-10">
              <%= text_field_tag 'pointname', '', size: 75, class: "form-control",placeholder: "name" %>
            </div>
          </div>

          <div class="form-group">
            <label for="inputName" class="col-lg-2 control-label">Number</label>
            <div class="col-lg-10">
              <%= text_field_tag 'phonenum', '', size: 75, class: "form-control",placeholder: "011" %>
            </div>
          </div>

          <div class="form-group">
            <label for="inputlocation" class="col-lg-2 control-label">Location</label>
            <div class="col-lg-10">
              <%= text_field_tag 'pointwhere','', size: 75, class: "form-control", placeholder: "location" %>
            </div>
          </div>

          <div class="form-group">
            <label for="textArea" class="col-lg-2 control-label">Wool</label>
            <div class="col-lg-10">
              <%= text_field_tag 'pointwhat', '', size: 75, class: "form-control",placeholder: "wool" %>
              <span class="help-block">A longer block of help text that breaks onto a new line and may extend beyond one line.</span>
            </div>
          </div>


        </fieldset>
        </div>




      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= submit_tag "Send", 'data-disable-with' => 'Sending', class: 'btn btn-primary' %>
        </div>
      <%end%>
    </div>
  </div>

app/views/woolentries/modalparts/_editwoolmodal.html.erb
<div id="editwoolmodal" class="modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
        <h4 class="modal-title">Add new wool Location</h4>
      </div>
      <div class="modal-body">


<%= form_tag woolentry_path(@cwool), :method => :put, :remote => :true, :class => "form-horizontal", :id => 'editform' do -%>

<fieldset>
  <legend>Legend</legend>
  <div class="form-group">
    <label for="inputName" class="col-lg-2 control-label">Name</label>
    <div class="col-lg-10">
      <%= text_field_tag 'pointname', @cwool.person, size: 75, class: "form-control",placeholder: "name" %>
    </div>
  </div>

  <div class="form-group">
    <label for="inputName" class="col-lg-2 control-label">Number</label>
    <div class="col-lg-10">
      <%= text_field_tag 'phonenum', @cwool.phonenum, size: 75, class: "form-control",placeholder: "011" %>
    </div>
  </div>

  <div class="form-group">
    <label for="inputlocation" class="col-lg-2 control-label">Location</label>
    <div class="col-lg-10">
      <%= text_field_tag 'pointwhere',"#{@cwool.lat} , #{@cwool.long}", size: 75, class: "form-control", placeholder: "location" %>
    </div>
  </div>

  <div class="form-group">
    <label for="textArea" class="col-lg-2 control-label">Wool</label>
    <div class="col-lg-10">
      <%= text_field_tag 'pointwhat', @cwool.desc, size: 75, class: "form-control",placeholder: "wool" %>
      <span class="help-block">A longer block of help text that breaks onto a new line and may extend beyond one line.</span>
    </div>
  </div>






</div>




</div>

<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  <%= submit_tag "Update", 'data-disable-with' => 'Updating', class: 'btn btn-primary',:onclick => "$('#editform').submit();$('#buttonforedit').prop('disabled',true);$('#buttonforedit').prop('value','Updating');", :id => 'buttonforedit' %>
  <!-- <%= submit_tag "Update", 'data-disable-with' => 'Updating', class: 'btn btn-primary' %> -->
</div>
</fieldset>

<%end%>
</div>
</div>

app/views/woolentries/modalparts/_listwoolmodal.html.erb
<div id="listwoolmodal" class="modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
        <h4 class="modal-title">Wool Entries</h4>
      </div>
      <div class="modal-body">


        <table class="table table-striped table-hover ">
          <thead>
            <tr>
              <th>#</th>
              <th>Donator Name</th>
              <th>Donator Phone Number</th>
              <th>Donator Wool</th>
              <th>Route to Address</th>
            </tr>
          </thead>
          <tbody>

        <% @wools.each do |l| %>
        <%= render 'listpart', :wools => l %>

        <%end %>

        </tbody>
        </table>







</div>




</div>


</fieldset>

</div>
</div>

app/views/woolentries/new.html.erb
<div class="col-lg-6">
  <%= form_tag({action: "create", method: "post", remote: true},{class: "form-horizontal" }) do %>

  <fieldset>
    <legend>New Wool</legend>
    <div class="form-group">
      <label for="inputName" class="col-lg-2 control-label">Name</label>
      <div class="col-lg-10">
        <%= text_field_tag 'pointname', '', size: 75, class: "form-control",placeholder: "name" %>
      </div>
    </div>

    <div class="form-group">
      <label for="inputName" class="col-lg-2 control-label">Number</label>
      <div class="col-lg-10">
        <%= text_field_tag 'phonenum', '', size: 75, class: "form-control",placeholder: "011" %>
      </div>
    </div>

    <div class="form-group">
      <label for="inputlocation" class="col-lg-2 control-label">Location</label>
      <div class="col-lg-10">
        <%= text_field_tag 'pointwhere','', size: 75, class: "form-control", placeholder: "location" %>
      </div>
    </div>

    <div class="form-group">
      <label for="textArea" class="col-lg-2 control-label">Wool</label>
      <div class="col-lg-10">
        <%= text_field_tag 'pointwhat', '', size: 75, class: "form-control",placeholder: "wool" %>
        <span class="help-block">A longer block of help text that breaks onto a new line and may extend beyond one line.</span>
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <%= submit_tag "Send", 'data-disable-with' => 'Sending', class: 'btn btn-primary' %>

      </div>
    </div>
  </fieldset>
<%end%>
</div>

app/views/woolentries/searchmap.js.erb
console.log("<%=@search%>");

markermoos = _.find(Gmaps.store.markers, function(obj) { return obj.serviceObject.person == "<%=@search%>" });
Gmaps.store.handler.map.centerOn(markermoos);
console.log("tes2t");

app/views/woolentries/update.js.erb
if (!(<%=@savable%>)) {
  $('.alert').remove();

$('#editwoolmodal').prepend("<p class='alert alert-danger'><%=@error%> </p>");
$('#buttonforedit').prop('disabled',false);
$('#buttonforedit').prop('value','Update');
 }
else {
$('#editwoolmodal').modal('hide');
$('#editwoolmodal').remove();
};